# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
  format_listener:
    rules:
      - {
          path: ^/,
          prefer_extension: true,
          fallback_format: json,
          priorities: [json],
        }

  routing_loader: false
