mercure:
  hubs:
    default:
      url: "http://localhost:8080/.well-known/mercure"
      public_url: "%env(MERCURE_PUBLIC_URL)%"
      jwt:
        secret: "%env(MERCURE_JWT_SECRET)%"
        publish: "*"
